// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomLeftWindowPanel: typeof import('./components/windowPanels/BottomLeftWindowPanel.vue')['default']
    BottomRightWindowPanel: typeof import('./components/windowPanels/BottomRightWindowPanel.vue')['default']
    CatoptricLogo: typeof import('./components/CatoptricLogo.vue')['default']
    CatotropicLogo: typeof import('./components/CatoptricLogo.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DpadController: typeof import('./components/dpad/DpadController.vue')['default']
    DragSelect: typeof import('./components/dragSelect/DragSelect.vue')['default']
    DragSelectMirrors: typeof import('./components/DragSelectMirrors.vue')['default']
    DragSelectOption: typeof import('./components/dragSelect/DragSelectOption.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    MenuAccordion: typeof import('./components/sidebar/menu/MenuAccordion.vue')['default']
    MenuMinimized: typeof import('./components/sidebar/menu/MenuMinimized.vue')['default']
    MiddleWindowPanel1: typeof import('./components/windowPanels/MiddleWindowPanel1.vue')['default']
    MiddleWindowPanel2: typeof import('./components/windowPanels/MiddleWindowPanel2.vue')['default']
    MirrorController: typeof import('./components/MirrorController.vue')['default']
    Navbar: typeof import('./components/navbar/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar/Sidebar.vue')['default']
    TopLeftWindowPanel: typeof import('./components/windowPanels/TopLeftWindowPanel.vue')['default']
    TopRightWindowPanel: typeof import('./components/windowPanels/TopRightWindowPanel.vue')['default']
    TopWindowPanel: typeof import('./components/windowPanels/TopWindowPanel.vue')['default']
    VaIconMenuCollapsed: typeof import('./components/icons/VaIconMenuCollapsed.vue')['default']
    VueDragSelect: typeof import('./components/dragSelect/DragSelect.vue')['default']
    VuesicLogo: typeof import('./components/VuesticLogo.vue')['default']
    VuesticLogo: typeof import('./components/VuesticLogo.vue')['default']
  }
}
