// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomLeft: typeof import('./components/windowPanels/BottomLeft/BottomLeft.vue')['default']
    BottomLeftDragSelect: typeof import('./components/windowPanels/BottomLeft/BottomLeftDragSelect.vue')['default']
    BottomLeftDragSelectOption: typeof import('./components/windowPanels/BottomLeft/BottomLeftDragSelectOption.vue')['default']
    BottomLeftWindowPanel: typeof import('./components/windowPanels/BottomLeftWindowPanel.vue')['default']
    BottomRight: typeof import('./components/windowPanels/BottomRight/BottomRight.vue')['default']
    BottomRightDragSelect: typeof import('./components/windowPanels/BottomRight/BottomRightDragSelect.vue')['default']
    BottomRightDragSelectOption: typeof import('./components/windowPanels/BottomRight/BottomRightDragSelectOption.vue')['default']
    BottomRightWindowPanel: typeof import('./components/windowPanels/BottomRightWindowPanel.vue')['default']
    CatoptricLogo: typeof import('./components/CatoptricLogo.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    DpadController: typeof import('./components/dpad/DpadController.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    LeftMost: typeof import('./components/windowPanels/LeftMost/LeftMost.vue')['default']
    LeftMostDragSelect: typeof import('./components/windowPanels/LeftMost/LeftMostDragSelect.vue')['default']
    LeftMostDragSelectOption: typeof import('./components/windowPanels/LeftMost/LeftMostDragSelectOption.vue')['default']
    MenuAccordion: typeof import('./components/sidebar/menu/MenuAccordion.vue')['default']
    MenuMinimized: typeof import('./components/sidebar/menu/MenuMinimized.vue')['default']
    MirrorController: typeof import('./components/MirrorController.vue')['default']
    Navbar: typeof import('./components/navbar/Navbar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RightMost: typeof import('./components/windowPanels/RightMost/RightMost.vue')['default']
    RightMostDragSelect: typeof import('./components/windowPanels/RightMost/RightMostDragSelect.vue')['default']
    RightMostDragSelectOption: typeof import('./components/windowPanels/RightMost/RightMostDragSelectOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar/Sidebar.vue')['default']
    TopLeft: typeof import('./components/windowPanels/TopLeft/TopLeft.vue')['default']
    TopLeftDragSelect: typeof import('./components/windowPanels/TopLeft/TopLeftDragSelect.vue')['default']
    TopLeftDragSelectOption: typeof import('./components/windowPanels/TopLeft/TopLeftDragSelectOption.vue')['default']
    TopRight: typeof import('./components/windowPanels/TopRight/TopRight.vue')['default']
    TopRightDragSelect: typeof import('./components/windowPanels/TopRight/TopRightDragSelect.vue')['default']
    TopRightDragSelectOption: typeof import('./components/windowPanels/TopRight/TopRightDragSelectOption.vue')['default']
    VaIconMenuCollapsed: typeof import('./components/icons/VaIconMenuCollapsed.vue')['default']
  }
}
